version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build: ./frontend
    ports:
      - "6666:6666"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

